use_frameworks!

target 'YBScrollSuspendManage_Example' do
  pod 'YBScrollSuspendManage', :path => '../'
  pod 'YBookmarkView'

  target 'YBScrollSuspendManage_Tests' do
    inherit! :search_paths

    
  end
end
